apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      containers:
        - name: swiggy-app
          image: whymanan/aiplanet:1.2
          ports:
            - containerPort: 3000